// apps/html-screen-builder/src/App.tsx
import React, { useState, useEffect } from 'react';
import { INITIAL_USERS, INITIAL_BROADCASTS } from './data';
import { User, Broadcast } from './types';
import UsersList from './components/UsersList';
import UserDetail from './components/UserDetail';
import Broadcasts from './components/Broadcasts';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Users, 
  Send, 
  Layout, 
  ShieldCheck, 
  Clock, 
  Database,
  ArrowRightLeft,
  ChevronRight,
  TrendingUp,
  Sliders,
  LogOut,
  AppWindow,
  FileBadge
} from 'lucide-react';

export default function App() {
  const [users, setUsers] = useState<User[]>(INITIAL_USERS);
  const [broadcasts, setBroadcasts] = useState<Broadcast[]>(INITIAL_BROADCASTS);
  const [selectedTab, setSelectedTab] = useState<'users' | 'broadcasts'>('users');
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [currentTime, setCurrentTime] = useState('');

  // Continuous Clock ticks in GMT+3 (Moscow)
  useEffect(() => {
    const updateTime = () => {
      const now = new Date();
      // Format as Moscow Time (GMT+3)
      const options: Intl.DateTimeFormatOptions = {
        timeZone: 'Europe/Moscow',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false
      };
      setCurrentTime(now.toLocaleTimeString('ru-RU', options));
    };
    
    updateTime();
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  }, []);

  // Update specific user details
  const handleUpdateUser = (updatedUser: User) => {
    setUsers(prev => prev.map(u => u.id === updatedUser.id ? updatedUser : u));
    setSelectedUser(updatedUser);
  };

  // Add manually created user
  const handleAddUser = (newUser: User) => {
    setUsers(prev => [newUser, ...prev]);
  };

  // Append composed broadcasts
  const handleAddBroadcast = (newBc: Broadcast) => {
    setBroadcasts(prev => [newBc, ...prev]);
  };

  // Delete broadcast item
  const handleDeleteBroadcast = (id: string) => {
    setBroadcasts(prev => prev.filter(bc => bc.id !== id));
  };

  return (
    <div className="flex h-screen w-full bg-[#0c141f] text-[#dce2f3] overflow-hidden font-sans select-none">
      
      {/* Sidebar Navigation */}
      <aside className="hidden lg:flex flex-col w-72 bg-[#090e15] border-r border-white/5 flex-shrink-0 z-20">
        
        {/* Core logotype & Brand identifier */}
        <div className="p-lg border-b border-white/5 space-y-2">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-primary to-secondary flex items-center justify-center font-black text-on-primary-fixed select-none text-sm shadow-md shadow-primary/20">
              П
            </div>
            <div>
              <h1 className="font-bold text-headline-sm text-sm tracking-wide text-on-surface uppercase pr-1">
                Психология Масштаба
              </h1>
              <span className="text-[10px] font-bold text-primary tracking-widest block uppercase">
                Админ-Консоль PML
              </span>
            </div>
          </div>
          
          <div className="flex items-center gap-1.5 pt-1">
            <span className="inline-flex w-2 h-2 rounded-full bg-secondary animate-pulse"></span>
            <span className="text-[10px] text-on-surface-variant font-mono font-bold uppercase tracking-wider">
              Сервер: Активен (Port 3000)
            </span>
          </div>
        </div>

        {/* Tab links section */}
        <nav className="p-md flex-1 space-y-1.5 overflow-y-auto">
          <button
            onClick={() => {
              setSelectedTab('users');
              setSelectedUser(null);
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all cursor-pointer ${
              selectedTab === 'users' && !selectedUser
                ? 'bg-primary-container text-on-primary-container font-semibold shadow-sm'
                : 'text-on-surface-variant hover:bg-white/5 hover:text-on-surface'
            }`}
          >
            <div className="flex items-center gap-3">
              <Users size={18} className={selectedTab === 'users' ? 'text-primary' : 'text-on-surface-variant'} />
              <span className="text-sm font-label-md">Пользователи бота</span>
            </div>
            <span className="text-[10px] font-semibold font-mono bg-white/5 px-2 py-0.5 rounded-full text-on-surface-variant">
              {users.length}
            </span>
          </button>

          <button
            onClick={() => {
              setSelectedTab('broadcasts');
              setSelectedUser(null);
            }}
            className={`w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all cursor-pointer ${
              selectedTab === 'broadcasts'
                ? 'bg-primary-container text-on-primary-container font-semibold shadow-sm'
                : 'text-on-surface-variant hover:bg-white/5 hover:text-on-surface'
            }`}
          >
            <div className="flex items-center gap-3">
              <Send size={18} className={selectedTab === 'broadcasts' ? 'text-primary' : 'text-on-surface-variant'} />
              <span className="text-sm font-label-md">Конструктор рассылок</span>
            </div>
            <span className="text-[10px] font-semibold font-mono bg-white/5 px-2 py-0.5 rounded-full text-on-surface-variant">
              {broadcasts.length}
            </span>
          </button>

          {/* Collapsible details shortcut */}
          {selectedUser && (
            <motion.div 
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              className="pt-4 border-t border-white/5 mt-4 space-y-md"
            >
              <span className="text-[10px] font-bold text-on-surface-variant uppercase tracking-wider px-4 block">Текущий участник</span>
              <div 
                onClick={() => setSelectedTab('users')}
                className="mx-2 p-2 bg-primary/10 border border-primary/20 rounded-xl flex items-center justify-between cursor-pointer group"
              >
                <div className="truncate pr-2">
                  <p className="text-xs font-semibold text-on-surface truncate">{selectedUser.fullName}</p>
                  <p className="text-[10px] font-mono text-primary truncate">{selectedUser.username}</p>
                </div>
                <ChevronRight size={14} className="text-primary group-hover:translate-x-1 transition-transform flex-shrink-0" />
              </div>
            </motion.div>
          )}
        </nav>

        {/* Sidebar Footer admin summary info */}
        <div className="p-lg border-t border-white/5 space-y-3 bg-white/2">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-full bg-surface-container-highest border border-white/10 flex items-center justify-center font-bold text-xs text-primary shadow">
              AD
            </div>
            <div>
              <p className="text-xs font-semibold text-on-surface leading-tight">Администратор PML</p>
              <p className="text-[10px] text-on-surface-variant">access_level: superadmin</p>
            </div>
          </div>
          
          <div className="flex gap-2">
            <div className="flex-grow p-2 rounded bg-surface-container-low text-center border border-white/5">
              <span className="text-[9px] text-on-surface-variant block uppercase font-bold tracking-wider">БД статус</span>
              <span className="text-xs font-bold text-secondary flex items-center justify-center gap-1 mt-0.5 font-mono">
                <Database size={10} /> Sync (OK)
              </span>
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content Workspace viewport */}
      <div className="flex-grow flex flex-col min-w-0 bg-[#0c141f] overflow-hidden">
        
        {/* Dynamic header row metadata */}
        <header className="h-16 border-b border-white/5 bg-[#090e15]/40 backdrop-blur-xl flex items-center justify-between px-lg z-10 flex-shrink-0">
          
          {/* Mobile responsive sidebar tab anchors drawer triggers */}
          <div className="flex items-center gap-md lg:hidden">
            <div className="w-7 h-7 rounded bg-gradient-to-tr from-primary to-secondary flex items-center justify-center font-black text-on-primary-fixed text-xs select-none shadow">
              П
            </div>
            <div className="flex bg-surface-container border border-white/5 p-1 rounded-xl">
              <button
                onClick={() => {
                  setSelectedTab('users');
                  setSelectedUser(null);
                }}
                className={`py-1.5 px-3 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                  selectedTab === 'users' ? 'bg-primary-container text-on-primary-container' : 'text-on-surface-variant'
                }`}
              >
                Пользователи
              </button>
              <button
                onClick={() => {
                  setSelectedTab('broadcasts');
                  setSelectedUser(null);
                }}
                className={`py-1.5 px-3 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                  selectedTab === 'broadcasts' ? 'bg-primary-container text-on-primary-container' : 'text-on-surface-variant'
                }`}
              >
                Рассылки
              </button>
            </div>
          </div>

          <div className="hidden lg:flex items-center gap-2 font-mono text-[11px] text-on-surface-variant">
            <span className="bg-surface-container-highest text-[#65bdff]/90 px-2 py-0.5 rounded font-bold uppercase border border-white/5">
              dev-preview
            </span>
            <span className="text-on-surface-variant/40">|</span>
            <span className="flex items-center gap-1 select-all cursor-pointer">
              <span className="material-symbols-outlined text-[14px]">link</span>
              pml-bot-production
            </span>
          </div>

          {/* Moscow time real clock widget */}
          <div className="flex items-center gap-3">
            <div className="bg-primary/5 border border-primary/20 px-3.5 py-1.5 rounded-xl flex items-center gap-2 font-mono text-xs text-primary shadow-inner">
              <Clock size={13} className="text-primary" />
              <span>МСК (GMT+3):</span>
              <strong className="tracking-widest tabular-nums">{currentTime || "00:00:00"}</strong>
            </div>
          </div>
        </header>

        {/* Scrollable primary card viewport body */}
        <main className="flex-1 overflow-y-auto px-lg py-lg custom-scrollbar">
          <AnimatePresence mode="wait">
            {selectedTab === 'users' ? (
              selectedUser ? (
                <motion.div
                  key="detail"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ duration: 0.2 }}
                >
                  <UserDetail 
                    user={selectedUser} 
                    onBack={() => setSelectedUser(null)} 
                    onUpdateUser={handleUpdateUser}
                  />
                </motion.div>
              ) : (
                <motion.div
                  key="list"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.15 }}
                >
                  <UsersList 
                    users={users} 
                    onSelectUser={(u) => setSelectedUser(u)} 
                    onAddUser={handleAddUser}
                  />
                </motion.div>
              )
            ) : (
              <motion.div
                key="broadcasts"
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.2 }}
              >
                <Broadcasts 
                  users={users}
                  broadcasts={broadcasts}
                  onAddBroadcast={handleAddBroadcast}
                  onDeleteBroadcast={handleDeleteBroadcast}
                />
              </motion.div>
            )}
          </AnimatePresence>
        </main>
      </div>
    </div>
  );
}

// apps/admin-mini-app/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useTelegram } from './composables/useTelegram.js'

// Lucide Vue Icons
import { 
  Users, 
  Send, 
  Clock, 
  Database,
  ChevronRight,
  Sparkles,
  ShieldCheck,
  AppWindow,
  FileBadge
} from '@lucide/vue'

// Mock initial data
import { initialUsers, initialBroadcasts } from './mockData.js'

// Import components
import DashboardStats from './components/DashboardStats.vue'
import UserList from './components/UserList.vue'
import UserProfileModal from './components/UserProfileModal.vue'
import AddUserModal from './components/AddUserModal.vue'
import BroadcastConstructor from './components/BroadcastConstructor.vue'

const { initApp, haptic } = useTelegram()

// Tabs navigation: 'users', 'broadcasts'
const currentTab = ref('users')

// Reactive database states
const users = ref([])
const broadcasts = ref([])

// Modals/Drawers toggle states
const selectedUser = ref(null)
const isProfileOpen = ref(false)
const isAddModalOpen = ref(false)

// Toast notification
const showToast = ref(false)
const toastMessage = ref('')

// Live Moscow Time Clock
const currentTime = ref('')
function updateTime() {
  const now = new Date()
  const options = {
    timeZone: 'Europe/Moscow',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false
  }
  currentTime.value = now.toLocaleTimeString('ru-RU', options)
}

onMounted(() => {
  // Initialize Telegram SDK
  initApp()
  
  // Start clock
  updateTime()
  setInterval(updateTime, 1000)

  // Load from localStorage or use mock initial data
  const cachedBroadcasts = localStorage.getItem('pml_admin_broadcasts')

  users.value = []

  if (cachedBroadcasts) {
    broadcasts.value = JSON.parse(cachedBroadcasts)
  } else {
    broadcasts.value = initialBroadcasts
    localStorage.setItem('pml_admin_broadcasts', JSON.stringify(initialBroadcasts))
  }
})

function switchTab(tab) {
  haptic()
  currentTab.value = tab
}

// User Actions
function selectUser(user) {
  haptic()
  selectedUser.value = user
  isProfileOpen.value = true
}

function handleSaveUser(updatedUser) {
  const index = users.value.findIndex(u => u.id === updatedUser.id)
  if (index !== -1) {
    users.value[index] = updatedUser
    localStorage.setItem('pml_admin_users', JSON.stringify(users.value))
  }
}

function handleAddUser(newUser) {
  haptic()
  newUser.id = Date.now()
  users.value.unshift(newUser)
  localStorage.setItem('pml_admin_users', JSON.stringify(users.value))
  triggerToast(`Пользователь ${newUser.full_name} успешно добавлен в базу!`)
}

// Broadcast Actions
function handleAddBroadcast(newLog) {
  haptic()
  broadcasts.value.unshift(newLog)
  localStorage.setItem('pml_admin_broadcasts', JSON.stringify(broadcasts.value))
}

function handleDeleteBroadcast(id) {
  haptic()
  broadcasts.value = broadcasts.value.filter(b => b.id !== id)
  localStorage.setItem('pml_admin_broadcasts', JSON.stringify(broadcasts.value))
  triggerToast(`Рассылка ${id} удалена из системы!`)
}

function triggerToast(msg) {
  toastMessage.value = msg
  showToast.value = true
  setTimeout(() => {
    showToast.value = false
  }, 3000)
}
</script>

<template>
  <div class="flex h-screen w-full bg-[#0c141f] text-[#dce2f3] overflow-hidden font-sans select-none">
    
    <!-- Sidebar Navigation - Desktop view -->
    <aside class="hidden md:flex flex-col w-72 bg-[#090e15] border-r border-white/5 flex-shrink-0 z-20">
      
      <!-- Core logotype & Brand identifier -->
      <div class="p-lg border-b border-white/5 space-y-2">
        <div class="flex items-center gap-2">
          <div class="w-8 h-8 rounded-lg bg-gradient-to-tr from-primary to-secondary flex items-center justify-center font-black text-on-primary-fixed select-none text-sm shadow-md shadow-primary/20">
            П
          </div>
          <div>
            <h1 class="font-bold text-sm tracking-wide text-on-surface uppercase pr-1">
              Психология Масштаба
            </h1>
            <span class="text-[10px] font-bold text-primary tracking-widest block uppercase">
              Админ-Консоль PML
            </span>
          </div>
        </div>
        
        <div class="flex items-center gap-1.5 pt-1">
          <span class="inline-flex w-2 h-2 rounded-full bg-secondary animate-pulse"></span>
          <span class="text-[10px] text-on-surface-variant font-mono font-bold uppercase tracking-wider">
            Сервер: Активен (Port 3000)
          </span>
        </div>
      </div>

      <!-- Tab links section -->
      <nav class="p-md flex-1 space-y-1.5 overflow-y-auto">
        <button
          @click="switchTab('users')"
          :class="[
            'w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all cursor-pointer border border-transparent',
            currentTab === 'users'
              ? 'bg-primary-container text-on-primary-container font-semibold shadow-sm border-primary/20'
              : 'text-on-surface-variant hover:bg-white/5 hover:text-on-surface'
          ]"
        >
          <div class="flex items-center gap-3">
            <Users :size="18" :class="currentTab === 'users' ? 'text-primary' : 'text-on-surface-variant'" />
            <span class="text-sm font-semibold">Пользователи бота</span>
          </div>
          <span class="text-[10px] font-semibold font-mono bg-white/5 px-2 py-0.5 rounded-full text-on-surface-variant">
            {{ users.length }}
          </span>
        </button>

        <button
          @click="switchTab('broadcasts')"
          :class="[
            'w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all cursor-pointer border border-transparent',
            currentTab === 'broadcasts'
              ? 'bg-primary-container text-on-primary-container font-semibold shadow-sm border-primary/20'
              : 'text-on-surface-variant hover:bg-white/5 hover:text-on-surface'
          ]"
        >
          <div class="flex items-center gap-3">
            <Send :size="18" :class="currentTab === 'broadcasts' ? 'text-primary' : 'text-on-surface-variant'" />
            <span class="text-sm font-semibold">Конструктор рассылок</span>
          </div>
          <span class="text-[10px] font-semibold font-mono bg-white/5 px-2 py-0.5 rounded-full text-on-surface-variant">
            {{ broadcasts.length }}
          </span>
        </button>
      </nav>

      <!-- Sidebar Footer admin summary info -->
      <div class="p-lg border-t border-white/5 space-y-3 bg-white/2">
        <div class="flex gap-2">
          <div class="flex-grow p-2 rounded bg-surface-container-low text-center border border-white/5">
            <span class="text-[9px] text-on-surface-variant block uppercase font-bold tracking-wider">БД статус</span>
            <span class="text-xs font-bold text-secondary flex items-center justify-center gap-1 mt-0.5 font-mono">
              <Database :size="10" /> Sync (OK)
            </span>
          </div>
        </div>
      </div>
    </aside>

    <!-- Main Content Workspace viewport -->
    <div class="flex-grow flex flex-col min-w-0 bg-[#0c141f] overflow-hidden">
      
      <!-- Dynamic header row metadata -->
      <header class="h-16 border-b border-white/5 bg-[#090e15]/40 backdrop-blur-xl flex items-center justify-between px-4 md:px-6 z-10 flex-shrink-0">
        
        <!-- Mobile responsive navigation -->
        <div class="flex items-center justify-between w-full md:hidden">
          <div class="w-7 h-7 rounded bg-gradient-to-tr from-primary to-secondary flex items-center justify-center font-black text-on-primary-fixed text-xs select-none shadow">
            П
          </div>
          <div class="flex bg-surface-container border border-white/5 p-1 rounded-xl">
            <button
              @click="switchTab('users')"
              :class="[
                'py-1.5 px-3 rounded-lg text-xs font-semibold transition-all cursor-pointer',
                currentTab === 'users' ? 'bg-primary-container text-on-primary-container' : 'text-on-surface-variant'
              ]"
            >
              Пользователи
            </button>
            <button
              @click="switchTab('broadcasts')"
              :class="[
                'py-1.5 px-3 rounded-lg text-xs font-semibold transition-all cursor-pointer',
                currentTab === 'broadcasts' ? 'bg-primary-container text-on-primary-container' : 'text-on-surface-variant'
              ]"
            >
              Рассылки
            </button>
          </div>
        </div>

        <div class="hidden md:flex items-center gap-2 font-mono text-[11px] text-on-surface-variant">
          <span class="bg-surface-container-highest text-[#65bdff]/90 px-2 py-0.5 rounded font-bold uppercase border border-white/5">
            dev-preview
          </span>
          <span class="text-on-surface-variant/40">|</span>
          <span class="flex items-center gap-1 select-all cursor-pointer">
            <span class="material-symbols-outlined text-[14px]">link</span>
            pml-bot-production
          </span>
        </div>

        <!-- Moscow time real clock widget -->
        <div class="hidden md:flex items-center gap-3">
          <div class="bg-primary/5 border border-primary/20 px-3.5 py-1.5 rounded-xl flex items-center gap-2 font-mono text-xs text-primary shadow-inner">
            <Clock :size="13" class="text-primary" />
            <span>МСК (GMT+3):</span>
            <strong class="tracking-widest tabular-nums">{{ currentTime || "00:00:00" }}</strong>
          </div>
        </div>
      </header>

      <!-- Scrollable primary card viewport body -->
      <main class="flex-1 overflow-y-auto px-4 md:px-6 py-4 md:py-6 pb-24 md:pb-6 custom-scrollbar">
        <Transition name="fade" mode="out-in">
          <!-- Tab 1: Users -->
          <div v-if="currentTab === 'users'" class="space-y-lg">
            <!-- Inline Detailed Profile View (like html-screen-builder) -->
            <div v-if="selectedUser && isProfileOpen" class="space-y-lg">
              <UserProfileModal 
                :user="selectedUser"
                @close="isProfileOpen = false; selectedUser = null"
                @saveUser="handleSaveUser"
              />
            </div>
            <div v-else class="space-y-lg">
              <DashboardStats :users="users" />
              <UserList 
                @usersLoaded="users = $event"
                @selectUser="selectUser"
                @openAddModal="isAddModalOpen = true"
              />
            </div>
          </div>

          <!-- Tab 2: Broadcasts -->
          <div v-else class="space-y-lg">
            <BroadcastConstructor 
              :users="users" 
              :broadcasts="broadcasts"
              @addBroadcast="handleAddBroadcast" 
              @deleteBroadcast="handleDeleteBroadcast"
            />
          </div>
        </Transition>
      </main>
    </div>

    <!-- Bottom Navigation Bar - Mobile view only (backup accessibility) -->
    <nav class="md:hidden fixed bottom-0 left-0 right-0 z-40 bg-[#0a1019]/95 backdrop-blur-md border-t border-white/5 p-2 flex justify-around select-none">
      <button 
        @click="switchTab('users')"
        :class="[
          'flex flex-col items-center gap-1 px-3 py-1.5 rounded-lg transition-all duration-150',
          currentTab === 'users' ? 'text-primary font-bold' : 'text-[#8a9db9]'
        ]"
      >
        <Users :size="16" />
        <span class="text-[9px] uppercase tracking-wider font-semibold">Пользователи</span>
      </button>

      <button 
        @click="switchTab('broadcasts')"
        :class="[
          'flex flex-col items-center gap-1 px-3 py-1.5 rounded-lg transition-all duration-150',
          currentTab === 'broadcasts' ? 'text-primary font-bold' : 'text-[#8a9db9]'
        ]"
      >
        <Send :size="16" />
        <span class="text-[9px] uppercase tracking-wider font-semibold">Рассылки</span>
      </button>
    </nav>

    <!-- Drawers & Modals Overlay layer -->
    <AddUserModal 
      :isOpen="isAddModalOpen"
      @close="isAddModalOpen = false"
      @addUser="handleAddUser"
    />

    <!-- Toast Notification -->
    <Transition name="fade">
      <div 
        v-if="showToast"
        class="fixed bottom-18 md:bottom-6 left-1/2 -translate-x-1/2 z-50 bg-[#121d2d] border border-primary/30 text-[#dce2f3] px-6 py-3 rounded-xl shadow-2xl text-xs font-semibold select-none flex items-center gap-3 glass-card"
      >
        <div class="w-5 h-5 rounded-full bg-primary/10 text-primary flex items-center justify-center">
          <Sparkles :size="12" />
        </div>
        {{ toastMessage }}
      </div>
    </Transition>

  </div>
</template>

<style>
.fade-enter-active, .fade-leave-active {
  transition: opacity 200ms ease, transform 200ms ease;
}
.fade-enter-from, .fade-leave-to {
  opacity: 0;
  transform: translateY(5px);
}
</style>
